# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

defaults: &defaults
  working_directory: ~/tmp
  docker:
    - image: circleci/node:8-browsers

version: 2
jobs:
  save_cache:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "yarn.lock" }}
          - dependency-cache-
      - run:
          name: install-dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - .cache/yarn
            - node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "yarn.lock" }}
          - dependency-cache-
      - run:
          name: install-dependencies
          command: yarn
      - run:
          name: build-project
          command: yarn build
      - store_artifacts:
          path: ./dist/
          prefix: builted-project
      - persist_to_workspace:
          root: ~/tmp
          paths: dist
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "yarn.lock" }}
          - dependency-cache-
      - run:
          name: install-dependencies
          command: yarn
      - run:
          name: run-unit-tests
          command: yarn test:ci
      - store_artifacts:
          path: ./coverage/
          prefix: tests-report
      - store_test_results:
          path: ./coverage/
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "yarn.lock" }}
          - dependency-cache-
      - run:
          name: install-dependencies
          command: yarn
      # - run:
      #     halt_build_on_fail: false
      #     name: angular-lint
      #     command: yarn lint:ci
      - store_artifacts:
          path: ./coverage/tslintout.json
          prefix: lint
  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: install-dependencies
          command: yarn
      - attach_workspace:
          at: /dist
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token $FIREBASE_TOKEN
workflows:
  version: 2
  build_and_test-flow:
    jobs:
      # - save_cache
      - build
      # - test
      # - lint
      - deploy:
          context: public
          requires:
            - build
            # - test
            # - lint
          # filters:
          #       branches:
          #         only: master
