# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
      # - environment:
        # CHROME_BIN: "/usr/bin/google-chrome"
    working_directory: ~/temp
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - dependency-cache-
      - run:
          name: install-dependencies
          command: yarn

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - .cache/yarn
            - node_modules
      - run:
          name: angular-build
          command: yarn build
      - run:
          name: angular-test
          command: yarn test:ci
      - store_artifacts:
          path: /coverage
          prefix: tests
      - run:
          name: angular-lint
          command: ng lint -t json > tslintout.json
      - store_artifacts:
          path: tslintout.json
          prefix: lint
